### ISSUE TITLE
Usage of RemoteSubgraph missing documentation

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-runtime#65]
Off top of my head need to
- Register the ComponentLoader in package.json
- Declare the remote runtime and component in package.json
- Instantiate a component with this name

**Comment by bergie** [comment]
Example here: https://github.com/c-base/ingress-table/blob/master/package.json#L59

**Comment by bergie** [comment]
WONTFIX. We should guide people to use [MsgFlo](https://msgflo.org/) for multi-process communications instead
